import type { NextPage } from 'next'
import ErrorPage from 'next/error'
import Head from 'next/head'

import { fetcher, Renderer } from '../lib'
import { ContentDataInterface } from '../lib/types'

const Page = ({ data }: ContentDataInterface) => {
  if (data.notFound) {
    return <ErrorPage statusCode={404} />
  }

  if (!data) return 'Loading...'

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Renderer {...data} />
    </>
  )
}

const Home: NextPage = data => {
  return <Page {...data} />
}

export const getServerSideProps = async ({ resolvedUrl }: string) => {
  const data = await fetcher(resolvedUrl)

  return { props: { data } }
}

export default Home
