import type { NextPage } from 'next'
import ErrorPage from 'next/error'
import Head from 'next/head'

import { Container } from '../components/'
import { fetcher, Renderer } from '../lib'
import { IData } from '../lib/types'

const Page = (data: IData) => {
  if (data.notFound) {
    return <ErrorPage statusCode={404} />
  }

  if (!data) return <Container>Loading...</Container>

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Renderer {...data} />
    </>
  )
}

const Home: NextPage<IData> = data => {
  return <Page {...data} />
}

export const getServerSideProps = async ({
  resolvedUrl: url,
}: {
  resolvedUrl: string
}) => {
  const data = await fetcher(url)

  return { props: { ...data } }
}

export default Home
